### ISSUE TITLE
Nuzzles command errors when [Var] is an int or int variable

### ISSUE THREAD

**Issue by madeforlosers** [TaserTheFox/EsoFur-Interpreter#24]
note: i meant [Var] in the title not [Var2] my mistake

Nuzzles seems to error when you tell it to jump down lines. it errors on line 101 saying `AttributeError: 'int' object has no attribute 'isdigit'`

also, If [Var] is a number in a string, it errors on line 102 saying `TypeError: unsupported operand type(s) for +=: 'int' and 'str'`,

(by the way, sorry if I'm bothering you. just trynna help out)

**Comment by TaserTheFox** [comment]
hm... can you provide me the program you tried to run?

also youre not bothering me at all, feel free to keep stressing the program out haha

**Comment by TaserTheFox** [comment]
so turns out, isdigit() expects a string, and is checking if said string is a digit, so `AttributeError: 'int' object has no attribute 'isdigit'` just means that it got an int instead of a string, so just add a check there...

**Comment by madeforlosers** [comment]
Sorry, i was asleep. 

here's what i was trying to run:
```
OwO What's This?
Notices Your Player1
Muzzles No Random Command
Notices Your Player2
Howl "Player 1: 1. Rock, 2. Paper, 3. Scissors"
Boop The User For Player1
Player1 Transforms Into Int
Howl "Player 2: 1. Rock, 2. Paper, 3. Scissors"
Boop The User For Player2
Player2 Transforms Into Int



Muzzles Checks
True Nuzzles 33

Marks Win
Howl [2J[Hwin!
Muzzles Using Escape Codes :3
Howl Player1
Howl Player2
QwQ

Marks Lose
Howl [2J[Hlose!
Muzzles Using Escape Codes :3
Howl Player1
Howl Player2
QwQ

Marks Check2
Player2==1 Nuzzles Tied
Player2==2 Nuzzles Lose
Player2==3 Nuzzles Win
QwQ

Marks Check3
Player2==1 Nuzzles Win
Player2==2 Nuzzles Tied
Player2==3 Nuzzles Lose
QwQ

Marks Check4
Player2==1 Nuzzles Lose
Player2==2 Nuzzles Win
Player2==3 Nuzzles Tied
QwQ


Player1==1 Nuzzles Check2
Player1==2 Nuzzles Check3
Player1==3 Nuzzles Check4

Howl ":("

QwQ
```

Its a simple rock paper scissors game thats 2 player. (heres another suggestion: a random number command) 
I got it to work by editing line 101 and 102 of main.py to be:
```
                        if str(label).isdigit():
                            i+=int(label);
```
instead of
```
                        if label.isdigit():
                            i+=label
```
because .isdigit() is for strings, and not for ints.

on line 99: 
```
                    label = self._assign(label.strip())
```
the function `self._assign(label.strip())` already detects if `label.strip()` is a digit and returns it as an int if so (line 227-228).
so `label` is now an int instead of a string. this might be the problem
(i tried my best to explain what might be going wrong. i'm not good with explanations. sorry if it's confusing)


Also, when outputting with Howl, strings with spaces in them cause nothing at all to be outputted. 
Also also, if you have multiple capital letters in a word, (example: `Howl "HEllo"` or `Howl "HeLlo"`) it returns a syntax error. don't know if that's intentional or not

**Comment by TaserTheFox** [comment]
using the escape codes for me seems to be causing issues, but thats an easy fix. also I think I might need to merge a branch thats actually compatible when I thought it wasn't

The no print howl with space is because of faulty code with the way i split the line in Howl command, fixed by setting a max split limit.

I'll commit these to the branch then merge, hopefully without any issues, so start using that branch please until I have merged the two.

About the random number generator, I'll see what i can find.

**Comment by madeforlosers** [comment]
alright

the escape codes work for me tho. must be bc of what im using

**Comment by TaserTheFox** [comment]
maybe because its actually displaying as those diamond question blocks for me? also yeah I would love to talk via discord, `Generic name#0144` yes, I still have not gotten rid of my discriminator.
also the capitalization requirements within strings shouldn't be required, but I think I didn't do anything about it cause I couldn't figure out how to get around it when I wrote the code.

as it turns out, the Import_Modules branch is bugged in that it thinks it closes a file for some reason? I cant seem to figure it out, ill open a new issue and close this issue as its issue is resolved hopefully

Summary:
Fixed Nuzzles; "the function self._assign(label.strip()) already detects if label.strip() is a digit and returns it as an int if so" ; Fixed
Fixed Howl; not printing when string contains spaces; Fixed
